FStarLang/pulse

share/pulse/examples/bug-reports/Bug33.fst
src/checker/Pulse.Checker.Admit.fst
src/checker/Pulse.Checker.Unreachable.fst
src/checker/Pulse.Elaborate.Core.fst
src/checker/Pulse.Soundness.Admit.fst
src/checker/Pulse.Soundness.fst
src/checker/Pulse.Typing.Combinators.fst
src/checker/Pulse.Typing.Combinators.fsti
src/checker/Pulse.Typing.FV.fst
src/checker/Pulse.Typing.LN.fst
src/checker/Pulse.Typing.Metatheory.Base.fst
src/checker/Pulse.Typing.fst
src/ocaml/plugin/generated/Pulse_Checker_Admit.ml
src/ocaml/plugin/generated/Pulse_Checker_Unreachable.ml
src/ocaml/plugin/generated/Pulse_Elaborate_Core.ml
src/ocaml/plugin/generated/Pulse_Typing.ml
src/ocaml/plugin/generated/Pulse_Typing_Combinators.ml
src/ocaml/plugin/generated/Pulse_Typing_Metatheory_Base.ml

The PR tweaks the checking for admit () so that we don't run the prover to prove any pre/post conditions. Fixes #33.

Fix for #33

---

lib/pulse/core/PulseCore.FractionalPermission.fst
lib/pulse/lib/Pulse.Lib.BigReference.fsti
lib/pulse/lib/Pulse.Lib.CancellableInvariant.fst
lib/pulse/lib/Pulse.Lib.CancellableInvariant.fsti
lib/pulse/lib/Pulse.Lib.Mutex.fst
lib/pulse/lib/Pulse.Lib.SpinLock.fst
lib/pulse/lib/Pulse.Lib.SpinLock.fsti
lib/pulse/lib/class/Pulse.Class.Duplicable.fst
lib/pulse/lib/class/Pulse.Class.Duplicable.fsti
lib/pulse/lib/pledge/Pulse.Lib.SmallTrade.fst
lib/pulse/lib/pledge/Pulse.Lib.SmallTrade.fsti
lib/pulse/lib/pledge/Pulse.Lib.Trade.fst
lib/pulse/lib/pledge/Pulse.Lib.Trade.fsti
share/pulse/examples/GhostStateMachine.fst
share/pulse/examples/by-example/ParallelIncrement.fst
share/pulse/examples/by-example/PulseTutorial.ParallelIncrement.fst
src/checker/Pulse.Checker.WithInv.fst
src/ocaml/plugin/generated/Pulse_Checker_WithInv.ml

- In Spinlock and CancellableInvariant, add a more general gather that does not require matching halves.
- Improve some error formatting
- Add a couple more trade operations (map, compose)
- Add a duplicable typeclass, so `dup p` becomes the canonical way of duplicating a resource.

Misc changes

---

lib/pulse/lib/Pulse.Lib.PCM.Product.fst
share/pulse/examples/Example.StructPCM.fst
share/pulse/examples/by-example/PulseTutorial.ParallelIncrement.fst

* A lib module for product pcm
* An example of a struct pcm, used to update fields of a struct in parallel
* Parallel increment (OWG) example with ghost state using a pcm
(Contains #41 as well :/)

Misc pcm libs and examples

---

src/checker/Pulse.Checker.AssertWithBinders.fst
src/checker/Pulse.Checker.Prover.fst
src/checker/Pulse.Syntax.Printer.fst
src/ocaml/plugin/generated/Pulse_Checker_AssertWithBinders.ml
src/ocaml/plugin/generated/Pulse_Checker_Prover.ml
src/ocaml/plugin/generated/Pulse_Syntax_Printer.ml

Fixing pretty printing of contexts

---

lib/pulse/lib/Pulse.Lib.CancellableInvariant.fst
lib/pulse/lib/Pulse.Lib.CancellableInvariant.fsti
lib/pulse/lib/Pulse.Lib.InvToken.fsti
lib/pulse/lib/Pulse.Lib.MutexToken.fst
lib/pulse/lib/Pulse.Lib.MutexToken.fsti
lib/pulse/lib/Pulse.Lib.SpinLock.fst
lib/pulse/lib/Pulse.Lib.SpinLock.fsti
lib/pulse/lib/Pulse.Lib.SpinLockToken.fst
lib/pulse/lib/Pulse.Lib.SpinLockToken.fsti
pulse2rust/src/Pulse2Rust.Extract.fst
pulse2rust/src/ocaml/generated/Pulse2Rust_Extract.ml
pulse2rust/tests/src/dpe_/dpe.rs
share/pulse/examples/dice/c.Makefile
share/pulse/examples/dice/common/Pulse_Lib_SpinLockToken.c
share/pulse/examples/dice/common/Pulse_Lib_SpinLockToken.h
share/pulse/examples/dice/dpe/DPE.fst
share/pulse/examples/dice/dpe/DPE.fsti
share/pulse/examples/dice/dpe/DPE_CBOR.fst

The PR adds an axiomatic interface for InvToken, and uses it to build top-level lock and mutex libraries. The libraries are then used in DPE.

Libraries for top-level spinlock and mutex, and their use in DPE

---

src/ocaml/plugin/FStar_Parser_Parse.mly

In preparation for FStarLang/FStar#3317

Fix parser

---

lib/pulse/lib/Pulse.Lib.LinkedList.fst
share/pulse/examples/bug-reports/Bug102.fst
share/pulse/examples/bug-reports/Bug102b.fst
share/pulse/examples/bug-reports/DependentTuples.fst
src/checker/Pulse.Checker.AssertWithBinders.fst
src/checker/Pulse.RuntimeUtils.fsti
src/ocaml/plugin/Pulse_RuntimeUtils.ml
src/ocaml/plugin/generated/Pulse_Checker_AssertWithBinders.ml

Make sure to only unfold the head once.
Fixes #102

Improving folding

---

src/ocaml/plugin/generated/PulseSyntaxExtension_Desugar.ml
src/ocaml/plugin/generated/PulseSyntaxExtension_Env.ml

https://github.com/FStarLang/FStar/pull/3330

snap, required for F* change

---

src/checker/Pulse.Checker.Abs.fst
src/checker/Pulse.Checker.AssertWithBinders.fst
src/checker/Pulse.Checker.Base.fst
src/checker/Pulse.Checker.Exists.fst
src/checker/Pulse.Checker.Pure.fst
src/checker/Pulse.Checker.Pure.fsti
src/checker/Pulse.Checker.Return.fst
src/ocaml/plugin/generated/Pulse_Checker_Abs.ml
src/ocaml/plugin/generated/Pulse_Checker_AssertWithBinders.ml
src/ocaml/plugin/generated/Pulse_Checker_Base.ml
src/ocaml/plugin/generated/Pulse_Checker_Exists.ml
src/ocaml/plugin/generated/Pulse_Checker_Pure.ml
src/ocaml/plugin/generated/Pulse_Checker_Return.ml

Needed for https://github.com/FStarLang/FStar/pull/3343

Update for fstar

---

lib/pulse/lib/Pulse.Lib.CancellableInvariant.fst
lib/pulse/lib/Pulse.Lib.ConditionVarWithCodes.fst
lib/pulse/lib/Pulse.Lib.Core.fst
lib/pulse/lib/Pulse.Lib.Core.fsti
lib/pulse/lib/Pulse.Lib.FlippableInv.fst
lib/pulse/lib/Pulse.Lib.FlippableInv.fsti
lib/pulse/lib/pledge/Pulse.Lib.InvList.fst
lib/pulse/lib/pledge/Pulse.Lib.SmallTrade.fst
share/pulse/examples/Invariant.fst
share/pulse/examples/PulseCorePaper.S2.Lock.fst
share/pulse/examples/bug-reports/Bug.Invariants.fst
share/pulse/examples/by-example/PulseTutorial.AtomicsAndInvariants.fst
share/pulse/examples/by-example/PulseTutorial.PCMParallelIncrement.fst
share/pulse/examples/by-example/PulseTutorial.ParallelIncrement.fst
share/pulse/examples/by-example/PulseTutorial.SpinLock.fst
share/pulse/examples/by-example/exercises/PulseTutorialExercises.AtomicsAndInvariants.fst
share/pulse/examples/parix/Promises.Examples3.fst
src/checker/Pulse.Checker.Abs.fst
src/checker/Pulse.Checker.Base.fst
src/checker/Pulse.Checker.Pure.fst
src/ocaml/plugin/generated/Pulse_Checker_Abs.ml
src/ocaml/plugin/generated/Pulse_Checker_Base.ml
src/ocaml/plugin/generated/Pulse_Checker_Pure.ml

A coercion `iname_list : list iname -> inames` gets us most of the way there. An operator `(@@)` is also sugar for `join_inames`

Using lists for `opens` declarations

---

lib/pulse/lib/Pulse.fst

Any opinion on this? I like the conciseness. Can it cause any issue?

Add a Pulse module, so we can just `open Pulse`

---

lib/pulse/lib/Pulse.Lib.AVLTree.fst
lib/pulse/lib/Pulse.Lib.AVLTree.fsti
lib/pulse/lib/Pulse.Lib.Spec.AVLTree.fst
lib/pulse/lib/Spec.AVLTree.fst

Pulse AVL tree implementation and interface. Spec is inspired from Steel.

Pulse AVL tree Implementation

---

.gitignore
CONTRIBUTING.md
share/pulse/examples/Makefile
share/pulse/examples/bug-reports/error-messages/Bug.DesugaringError.fst
share/pulse/examples/bug-reports/error-messages/Bug.DesugaringError.fst.expected
share/pulse/examples/bug-reports/error-messages/Makefile
src/ocaml/plugin/generated/PulseSyntaxExtension_ASTBuilder.ml
src/ocaml/plugin/pulseparser.mly
src/syntax_extension/PulseSyntaxExtension.ASTBuilder.fst

* Working around a menhir bug (?) reporting a wrong range in option(qual)
* Tweak error report to not have overlapping /masking ranges
* Add a test case for checking error messages and ranges

Fix reporting of ranges in desugaring errors

---

.devcontainer/rebuild-container-and-deploy.sh
src/ocaml/plugin/FStar_Parser_Parse.mly
src/ocaml/plugin/Pulse_Extract_CompilerLib.ml

This makes generated C code much more compact by reusing the karamel inlining logic.
Example diff from `ExtractionTest.c`:
```diff
diff --git a/old.c b/new.c
index d70776d3b..6d18a1df4 100644
--- a/old.c
+++ b/new.c
@@ -20,8 +20,7 @@ uint32_t ExtractionTest_zero(void)
void ExtractionTest_test_read_write(uint32_t *x)
{
-  uint32_t n = *x;
-  *x = n + 0U;
+  *x = *x + 0U;
}
void ExtractionTest_test_write_10(uint32_t *x)
@@ -39,32 +38,23 @@ void ExtractionTest_test_inner_ghost_fun(void)
void ExtractionTest_write10(uint32_t *x)
{
uint32_t ctr = 10U;
-  uint32_t ctr_1 = ctr;
-  bool cond = ctr_1 > 0U;
-  while (cond)
+  while (ctr > 0U)
{
*x = 2U;
ExtractionTest_test_read_write(x);
*x = 0U;
-    uint32_t ctr_2 = ctr;
-    ctr = ctr_2 - 1U;
-    uint32_t ctr_1 = ctr;
-    cond = ctr_1 > 0U;
+ …
```

Extraction: mark everything CInline

---

.scripts/check-snapshot-diff.sh
src/Makefile

To be called by check-world, too

Factoring out the snapshot diff check

---

src/ocaml/plugin/FStar_Parser_Parse.mly
src/ocaml/plugin/generated/PulseSyntaxExtension_ASTBuilder.ml
src/ocaml/plugin/pulseparser.mly
src/syntax_extension/PulseSyntaxExtension.ASTBuilder.fst

This is for https://github.com/FStarLang/FStar/pull/3453

Error api fixes

---

lib/pulse/lib/fstar.include

lib: add missing fstar.include

---

src/ocaml/plugin/generated/Pulse_Checker.ml
src/ocaml/plugin/generated/Pulse_Checker_Abs.ml
src/ocaml/plugin/generated/Pulse_Checker_Match.ml
src/ocaml/plugin/generated/Pulse_Checker_WithLocal.ml
src/ocaml/plugin/generated/Pulse_Checker_WithLocalArray.ml
src/ocaml/plugin/generated/Pulse_Extract_Main.ml
src/ocaml/plugin/generated/Pulse_Syntax_Base.ml
src/ocaml/plugin/generated/Pulse_Syntax_Printer.ml
src/ocaml/plugin/generated/Pulse_Typing_Env.ml

Just for https://github.com/FStarLang/FStar/pull/3569

snap for F* change

---

lib/pulse/core/PulseCore.IndirectionTheory.fst
lib/pulse/core/PulseCore.IndirectionTheory.fsti
lib/pulse/core/PulseCore.IndirectionTheoryActions.fst
lib/pulse/core/PulseCore.IndirectionTheorySep.fst
lib/pulse/core/PulseCore.IndirectionTheorySep.fsti
lib/pulse/core/PulseCore.KnotInstantiation.fst
lib/pulse/core/PulseCore.KnotInstantiation.fsti
lib/pulse/lib/Pulse.Lib.SeqMatch.fst
share/pulse/examples/NuPool.fst
share/pulse/examples/NuPool.fsti

Add missing copyright headers.

---

lib/common/Pulse.fst.config.json
lib/core/Pulse.fst.config.json

Assorted fixes for VS Code

---

lib/pulse/lib/Pulse.Lib.SeqMatch.fst
lib/pulse/lib/Pulse.Lib.SeqMatch.fsti

Most of them are inherited from `Pulse.Lib.OnRange`.

More lemmas about SeqMatch

---

.devcontainer/devcontainer.json
.devcontainer/fromscratch/devcontainer.json
.devcontainer/fromscratch/minimal.Dockerfile
.github/workflows/nightly.yml
.gitignore
.scripts/mk_package.sh
Makefile

Nightly builds to be published here https://github.com/FStarLang/pulse-nightly/

Restoring mac builds, packaging, devcontainer

---

pulse2rust/src/Pulse2Rust.Deps.fst
pulse2rust/src/Pulse2Rust.Env.fsti
pulse2rust/src/Pulse2Rust.Extract.fst
pulse2rust/src/Pulse2Rust.fst

pulse2rust: update after F* change

---

pulse2rust/src/Pulse2Rust.fst
src/syntax_extension/PulseSyntaxExtension.ASTBuilder.fst

https://github.com/FStarLang/FStar/pull/3740

Update for F* change

---

src/checker/Pulse.Main.fst
src/checker/Pulse.RuntimeUtils.fsti
src/ml/Pulse_RuntimeUtils.ml

Checker.Main: disabling admit for the pulse checker

---

lib/pulse/lib/Pulse.Lib.AVLTree.fst
lib/pulse/lib/Pulse.Lib.Deque.fst
lib/pulse/lib/Pulse.Lib.LinkedList.fst
lib/pulse/lib/Pulse.Lib.SeqMatch.fst
lib/pulse/lib/Pulse.Lib.Slice.Util.fst
lib/pulse/lib/Pulse.Lib.Sort.Merge.Slice.fst
lib/pulse/lib/Pulse.Lib.Task.fst
share/pulse/examples/PulseExample.UseBigRef.fst
share/pulse/examples/by-example/PulseTutorial.Ghost.fst
share/pulse/examples/by-example/PulseTutorial.LinkedList.fst
src/syntax_extension/PulseSyntaxExtension.Desugar.fst
test/Example.Slice.fst
test/MatchBasic.fst
test/Matches.fst
test/nolib/TupleFun.fst

We still have the restriction that patterns cannot be deep, but we can
at least use decent syntax.

desugar: support tuple and list patterns

---

test/bug-reports/Bug100.fst.output.expected
test/bug-reports/Bug267.fst.output.expected
test/bug-reports/Bug94.fst.output.expected

Lines in Prims moved after FStarLang/FStar#3760

Update expected output

---

src/checker/Pulse.Extract.Main.fst
test/Bug356.c.expected
test/Bug356.fst

Extract admit to admit.

---

src/checker/Pulse.Typing.Metatheory.Base.fst

The `admit_smt_queries` hid the incomplete pattern match.
cc @mtzguido

Add missing branch in st_equiv_weakening.

---

src/checker/Pulse.Typing.Env.fst
src/checker/Pulse.Typing.Env.fsti
src/checker/Pulse.Typing.Metatheory.Base.fst

Following up on #370, I went looking for admit_smt_queries and found several other functions with incomplete pattern matches.

Add more missing branches.

---

lib/pulse/lib/Pulse.Lib.BigReference.fsti
lib/pulse/lib/Pulse.Lib.Box.fsti
lib/pulse/lib/Pulse.Lib.CancellableInvariant.fsti
lib/pulse/lib/Pulse.Lib.DequeRef.fsti
lib/pulse/lib/Pulse.Lib.Forall.Util.fsti
lib/pulse/lib/Pulse.Lib.Forall.fsti
lib/pulse/lib/Pulse.Lib.GhostFractionalTable.fsti
lib/pulse/lib/Pulse.Lib.GhostPCMReference.fsti
lib/pulse/lib/Pulse.Lib.GhostReference.fst
lib/pulse/lib/Pulse.Lib.GhostReference.fsti
lib/pulse/lib/Pulse.Lib.GhostWitness.fsti
lib/pulse/lib/Pulse.Lib.GlobalVar.fsti
lib/pulse/lib/Pulse.Lib.HigherArray.fst
lib/pulse/lib/Pulse.Lib.HigherArray.fsti
lib/pulse/lib/Pulse.Lib.HigherGhostReference.fst
lib/pulse/lib/Pulse.Lib.HigherGhostReference.fsti
lib/pulse/lib/Pulse.Lib.LinkedList.fst
lib/pulse/lib/Pulse.Lib.LinkedList.fsti
src/checker/Pulse.Checker.Prover.Match.Base.fsti
test/BinderAttrs.fst

More pulse vals, an interface, a test for dropping binder attrs in Pulse decls (which we should fix)

Misc cleanups

---

src/checker/Pulse.Checker.Abs.fst
src/checker/Pulse.Checker.AssertWithBinders.fst
src/checker/Pulse.Checker.Base.fst
src/checker/Pulse.Checker.Exists.fst
src/checker/Pulse.Checker.Pure.fst
src/checker/Pulse.Checker.Pure.fsti
src/checker/Pulse.Checker.Return.fst
test/bug-reports/Bug273.fst

Needs https://github.com/FStarLang/FStar/pull/3801

Fix instantiation of implicits in return position

---

share/pulse/examples/by-example/PulseByExample.fst
share/pulse/examples/by-example/PulseTutorial.Array.fst
share/pulse/examples/by-example/PulseTutorial.AtomicsAndInvariants.fst
share/pulse/examples/by-example/PulseTutorial.Box.fst
share/pulse/examples/by-example/PulseTutorial.Conditionals.fst
share/pulse/examples/by-example/PulseTutorial.Existentials.fst
share/pulse/examples/by-example/PulseTutorial.Ghost.fst
share/pulse/examples/by-example/PulseTutorial.HigherOrder.fst
share/pulse/examples/by-example/PulseTutorial.ImplicationAndForall.fst
share/pulse/examples/by-example/PulseTutorial.Intro.fst
share/pulse/examples/by-example/PulseTutorial.LinkedList.fst
share/pulse/examples/by-example/PulseTutorial.Loops.fst
share/pulse/examples/by-example/PulseTutorial.ParallelIncrement.fst
share/pulse/examples/by-example/PulseTutorial.Ref.fst
share/pulse/examples/by-example/PulseTutorial.SpinLock.fst
share/pulse/examples/by-example/PulseTutorial.UserDefinedPredicates.fst

Mostly update snippet anchors + provide some more examples in AtomicsAndInvariants etc.

Update examples to match with revised text in PoP-in-FStar

---

src/ml/FStarC_Parser_Parse.mly
src/ml/PulseSyntaxExtension_Parser.ml

cf. https://github.com/FStarLang/FStar/pull/3888

Update F* parser + token translation

---

src/ml/FStarC_Parser_Parse.mly
src/ml/PulseSyntaxExtension_Parser.ml

For https://github.com/FStarLang/FStar/pull/3894

Update F* parser

---

lib/common/Pulse.Lib.Core.fsti
lib/pulse/lib/Pulse.Lib.Box.fst
lib/pulse/lib/Pulse.Lib.GhostReference.fst
lib/pulse/lib/Pulse.Lib.HigherReference.fst
share/pulse/examples/Quicksort.Task.fst
src/ml/FStarC_Parser_Parse.mly
src/ml/PulseSyntaxExtension_Parser.ml

For https://github.com/FStarLang/FStar/pull/3984

Update parser, and examples

---

Pulse.fst.config.json
README.md
lib/common/Pulse.fst.config.json
lib/core/Pulse.fst.config.json
lib/pulse/Pulse.fst.config.json
mk/boot.mk
mk/test.mk
pulse2rust/src/Pulse2Rust.fst.config.json
share/pulse/examples/Pulse.fst.config.json
src/checker/PulseChecker.fst.config.json
src/extraction/Extraction.fst.config.json
src/syntax_extension/PulseSyntaxExtension.fst.config.json
test/Cfg.fst.config.json
test/nolib/Cfg.fst.config.json

See https://github.com/FStarLang/FStar/pull/4008

Remove z3version override.
