FStarLang/pulse

lib/pulse/core/PulseCore.Action.fst, lib/pulse/core/PulseCore.Action.fsti, lib/pulse/core/PulseCore.Atomic.fst, lib/pulse/core/PulseCore.Atomic.fsti, lib/pulse/core/PulseCore.Memory.fst, lib/pulse/core/PulseCore.Memory.fsti, lib/pulse/lib/Pulse.Lib.Core.fst, lib/pulse/lib/Pulse.Lib.Core.fsti, share/pulse/examples/Quicksort.Base.fst
This PR provides three utilities for working with invariant names.
1 & 2. A form on injectivity on invariant names. Both these lemmas involve eliminating an `inv p` and so are in stt_atomic Unobservable, i.e., they are computation steps since they involve using the recall operator of underlying monotonic state monad. That's why I also provided it in two forms, since it's not possible to take the contrapositive of these computation steps.
```fstar
val distinct_invariants_have_distinct_names
(#p #q:vprop)
(i:inv p)
(j:inv q { (p =!= q) })
: stt_atomic (_:squash (name_of_inv i =!= name_of_inv j))
#Unobservable
emp_inames
emp
(fun _ -> emp)
```
```fstar
val invariant_name_identifies_invariant
(#p #q:vprop)
(i:inv p)
(j:inv q { name_of_inv i == name_of_inv j } )
: stt_atomic (squash (p == q /\ …
```
=> Some utilities on invariant names

lib/pulse/core/PulseCore.Action.fst, lib/pulse/core/PulseCore.Action.fsti, lib/pulse/core/PulseCore.Atomic.fst, lib/pulse/core/PulseCore.Atomic.fsti, lib/pulse/core/PulseCore.Memory.fst, lib/pulse/core/PulseCore.Memory.fsti, lib/pulse/core/PulseCore.MonotonicStateMonad.fst, lib/pulse/core/PulseCore.MonotonicStateMonad.fsti, lib/pulse/core/PulseCore.PreorderStateMonad.fst, lib/pulse/core/PulseCore.PreorderStateMonad.fsti
I'm starting to strengthen the definition of ghost computations so that we rule out improper uses of witness/recall by typing at the lowest levels in PulseCore itself, rather than by relying on abstraction higher up the stack.
Towards this end, the semantics now begins with PulseCore.PreorderStateMonad, a simple, axiom-free state monad, augmented with a two-state invariant that the state evolves according to a given preorder. This monad is not abstract---it's exposed as a reified state-passing function. MonotonicStateMonad *is* abstract and augments PreorderStateMonad with witness/recall.
Actions in heap, memory etc. that do not use invariants or witness recall are defined in PreorderStateMonad.
PulseCore.Action distinguishes two kinds of actions by an index: Reifiable and UsesInvariants, …
=> Enforcing in PulseCore that ghost computations cannot use witness/recall

lib/pulse/core/PulseCore.Action.fst, lib/pulse/core/PulseCore.Action.fsti, lib/pulse/core/PulseCore.Atomic.fst, lib/pulse/core/PulseCore.Atomic.fsti, lib/pulse/core/PulseCore.Heap.fst, lib/pulse/core/PulseCore.Heap.fsti, lib/pulse/core/PulseCore.Heap2.fst, lib/pulse/core/PulseCore.Heap2.fsti, lib/pulse/core/PulseCore.HeapLike.fst, lib/pulse/core/PulseCore.Memory.fst, lib/pulse/core/PulseCore.Memory.fsti
In PulseCore, Ghost functions were previously not semantically distinguished from other atomic .actions, although they were marked as erased. This meant that we needed an axiom to lift ghost functions (with non-informative results) to regular actions. With this PR, we no longer need that axiom.
The technical mechanism enabling this is to move to a bipartite heap PulseCore.Heap2, consisting of a concrete heap and a ghost erased heap. Ghost functions are proven to only mutate the erased heap, and ghost functions now have a model starting from Heap2 and going up through Memory, Action, and Atomic layers.
Note, although this led to removing the axiom, the proofs require quite a lot of boilerplate and duplication between the concrete and ghost heaps. Expect a follow-up PR trying to add some …
=> Ghost functions have a model supporting their erasure

lib/pulse/core/PulseCore.Action.fst, lib/pulse/core/PulseCore.Action.fsti, lib/pulse/core/PulseCore.Atomic.fsti, lib/pulse/core/PulseCore.Heap.fst, lib/pulse/core/PulseCore.Heap.fsti, lib/pulse/core/PulseCore.Heap2.fst, lib/pulse/core/PulseCore.Heap2.fsti, lib/pulse/core/PulseCore.Memory.fsti, lib/pulse/lib/Pulse.Lib.Core.fst, lib/pulse/lib/Pulse.Lib.Core.fsti
This is true by virtue of being in a PCM, where the unit is composable with any x. Remove the preconditions everywhere and call the lemma that proves this as needed.
=> Core: remove explicit preconditions for `compatible x x`

share/pulse/examples/bug-reports/Bug13.fst, src/checker/Pulse.Checker.Abs.fst, src/checker/Pulse.RuntimeUtils.fsti, src/ocaml/plugin/Pulse_RuntimeUtils.ml, src/ocaml/plugin/generated/Pulse_Checker_Abs.ml
=> Use HNF to normalize annotated computation types.

lib/pulse/lib/Pulse.Lib.HashTable.Spec.fst
I'm not sure what's different about Z3 on my machine, but verifying `Pulse.Lib.HashTable.Spec.fst` failed on the command-line for me.  (Weirdly enough, it worked fine in vscode.)
=> Bump rlimit.

lib/pulse/lib/class/Pulse.Class.Small.fst, lib/pulse/lib/class/Pulse.Class.Small.fsti
This class is amenable to be used in typeclass resolution, unlike the refinment encoding is_small. To be used is the automatic encoding of vprops.
=> Pulse.Class.Small: a class for small vprops

lib/pulse/lib/Pulse.Lib.Task.fsti, lib/pulse/lib/pledge/Pulse.Lib.Pledge.Simple.fst, lib/pulse/lib/pledge/Pulse.Lib.Pledge.Simple.fsti, lib/pulse/lib/pledge/Pulse.Lib.Pledge.fst, lib/pulse/lib/pledge/Pulse.Lib.Pledge.fsti, share/pulse/examples/PledgeArith.fst, share/pulse/examples/Quicksort.Task.fst, share/pulse/examples/parix/Async.fst, share/pulse/examples/parix/ParallelFor.fst, share/pulse/examples/parix/Promises.Examples3.fst, share/pulse/examples/parix/TaskPool.Examples.fst, share/pulse/examples/parix/UnixFork.fsti
No need for this Par namespace component
=> library: rename Pulse.Lib.Par.Pledge.* into Pulse.Lib.Pledge.*

lib/pulse/lib/Pulse.Lib.SpinLock.fst, lib/pulse/lib/Pulse.Lib.SpinLock.fsti
This proves that, if we have
lock_alive l #f1 v1 ** lock_alive l #f2 v2
then we can convert the second one to match the resource of the first, i.e.
lock_alive l #f1 v1 ** lock_alive l #f2 v1
Ideally we would get `v1==v2`, but I am not sure if that's provable. At least, it would require to bubble up some equalities from the model, including (I think) that if `(exists* x. f1 x) == (exists* x. f2 x)`, then `forall x. f1 x == f2 x`.
=> SpinLock: prove (a version of) the injectivity lemma

lib/pulse/core/PulseCore.Action.fst, lib/pulse/core/PulseCore.Action.fsti, lib/pulse/core/PulseCore.Heap2.fst, lib/pulse/core/PulseCore.Heap2.fsti, lib/pulse/core/PulseCore.Memory.fst, lib/pulse/core/PulseCore.Memory.fsti, lib/pulse/core/PulseCore.TwoLevelHeap.fst, lib/pulse/core/PulseCore.TwoLevelHeap.fsti, lib/pulse/lib/Pulse.Lib.BigGhostReference.fst, lib/pulse/lib/Pulse.Lib.CancellableInvariant.fst, lib/pulse/lib/Pulse.Lib.Core.fst, lib/pulse/lib/Pulse.Lib.Core.fsti, lib/pulse/lib/Pulse.Lib.HigherArray.fst, lib/pulse/lib/Pulse.Lib.HigherGhostReference.fst
Expose core_ref and core_ghost_ref, the base type of concrete and ghost memory addresses, rather than only their parameterized versions, since the parameters are actually meaningless.
This is useful in Pulse.Lib.HigherArray, especially since F* PR #3253 https://github.com/FStarLang/FStar/pull/3253
=> Nik injectivity

lib/pulse/core/PulseCore.Heap.fst, lib/pulse/core/PulseCore.Heap.fsti, lib/pulse/core/PulseCore.Memory.fst
The PR tries to remove fractional permissions from the PulseCore heap cells. Instead it defines a cell being full as the cell value satisfying the pcm refine predicate.
This turned out to be a purely internal change, as in we can provide the same interface as before.
=> Trying to remove fractional permission from the cells in PulseCore heap

share/pulse/examples/DropEmp.fst, src/checker/Pulse.Checker.AssertWithBinders.fst, src/checker/Pulse.Checker.Prover.IntroPure.fst, src/checker/Pulse.Checker.Prover.fst, src/checker/Pulse.PP.fst, src/checker/Pulse.PP.fsti, src/checker/Pulse.Typing.Env.fst, src/checker/Pulse.Typing.Util.fst, src/checker/Pulse.Typing.Util.fsti, src/ocaml/plugin/generated/Pulse_Checker_Abs.ml, src/ocaml/plugin/generated/Pulse_Checker_AssertWithBinders.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_IntroPure.ml, src/ocaml/plugin/generated/Pulse_Checker_Pure.ml, src/ocaml/plugin/generated/Pulse_Checker_Rewrite.ml, src/ocaml/plugin/generated/Pulse_Checker_WithInv.ml, src/ocaml/plugin/generated/Pulse_PP.ml, src/ocaml/plugin/generated/Pulse_Typing_Combinators.ml, src/ocaml/plugin/generated/Pulse_Typing_Env.ml, src/ocaml/plugin/generated/Pulse_Typing_Util.ml
- Printing the substituted vprop when the prover fails.
- A better check for empty vprops at the end of a function, using core_check_equiv_nosmt
- Pretty printing improvements
=> Misc usablity improvement

lib/pulse/lib/Pulse.Lib.Mutex.fst, lib/pulse/lib/Pulse.Lib.Mutex.fsti, pulse2rust/src/Pulse2Rust.Extract.fst, pulse2rust/src/Pulse2Rust.Rust.Syntax.fst, pulse2rust/src/Pulse2Rust.Rust.Syntax.fsti, pulse2rust/src/ocaml/generated/Pulse2Rust_Extract.ml, pulse2rust/src/ocaml/generated/Pulse2Rust_Rust_Syntax.ml, pulse2rust/src/ocaml/rust/src/lib.rs, pulse2rust/tests/src/dpe_/dpe.rs, pulse2rust/tests/src/dpe_/pulse_lib_hashtable.rs, share/pulse/examples/dice/dpe/DPE.fst
This PR tweaks the Mutex API to provide a mutex guard upon locking. Mutex guard is a ref-like type that provides read, write, replace, and a pts_to predicate. The change is quite superficial and is only intended to simplify Rust extraction.
=> Mutex guard based Mutex API

lib/pulse/lib/Pulse.Lib.HigherArray.fst, share/pulse/examples/CustomSyntax.fst, share/pulse/examples/Example.ImplicitBinders.fst, share/pulse/examples/ZetaHashAccumulator.fst, share/pulse/examples/bug-reports/Bug.Invariants.fst, share/pulse/examples/by-example/PulseTutorial.Array.fst, share/pulse/examples/by-example/PulseTutorial.ImplicationAndForall.fst, share/pulse/examples/by-example/PulseTutorial.LinkedList.fst, share/pulse/examples/dice/cbor/CDDLExtractionTest.Assume.fst, share/pulse/examples/dice/cbor/CDDLExtractionTest.Bytes.fst, share/pulse/examples/dice/cbor/CDDLExtractionTest.BytesDirect.fst, share/pulse/examples/dice/cbor/CDDLExtractionTest.BytesUnwrapped.fst, share/pulse/examples/dice/cbor/CDDLExtractionTest.BytesVeryDirect.fst, share/pulse/examples/dice/cbor/CDDLExtractionTest.BytesVeryDirectFail.fst, share/pulse/examples/dice/cbor/CDDLExtractionTest.Choice.fst, share/pulse/examples/dice/dpe/DPE_CBOR.fst, share/pulse/examples/parix/Promises.Examples3.fst, src/ocaml/plugin/generated/PulseSyntaxExtension_Desugar.ml, src/syntax_extension/PulseSyntaxExtension.Desugar.fst
```
//
// Pulse checker adds implicit binders for 'n1 and 'n2
//   at erased types
//
fn swap (r1 r2:ref U32.t)
requires
pts_to r1 'n1 **
pts_to r2 'n2
ensures
pts_to r1 'n2 **
pts_to r2 'n1
//
// Since p and n are non tick variables,
//   this gives an error "Identifiers (n, p) not found, consider adding them as binders"
//
[@@ expect_failure]
fn test_read (r:ref U32.t)
requires pts_to r #p n
returns x : U32.t
ensures pts_to r #p x
```
=> Adding only tick variables as implicit binders

lib/pulse/lib/Pulse.Lib.OnRange.fst, lib/pulse/lib/Pulse.Lib.OnRange.fsti, lib/pulse/lib/Pulse.Lib.Stick.Util.fst, lib/pulse/lib/Pulse.Lib.Stick.fsti, share/pulse/examples/dice/dpe/DPE.Messages.Parse.fst, share/pulse/examples/dice/dpe/DPE_CBOR.fst
The PR implements the Pulse.Lib.OnRange interface. It also tweaks the Pulse.Lib.Stick interface to provide intro and elim in terms of `@==>`, to eliminate some rewrites in the client code.
=> Pulse.Lib.OnRange implementation and tweaks to stick interface

lib/pulse/lib/Pulse.Lib.Array.Core.fsti, share/pulse/Makefile.include-base, share/pulse/examples/c/PulsePointStruct.fst, share/pulse/examples/dice/dpe/DPE.Messages.Parse.fst, src/checker/Pulse.Checker.Base.fst, src/checker/Pulse.Checker.Bind.fst, src/checker/Pulse.Checker.Prover.Substs.fst, src/checker/Pulse.Checker.Prover.Substs.fsti, src/checker/Pulse.Checker.Pure.fst, src/checker/Pulse.Elaborate.Pure.fst, src/checker/Pulse.Elaborate.fst, src/checker/Pulse.Soundness.Bind.fst, src/checker/Pulse.Soundness.Comp.fst, src/checker/Pulse.Soundness.STEquiv.fst, src/checker/Pulse.Soundness.fst, src/checker/Pulse.Typing.Combinators.fst, src/checker/Pulse.Typing.FV.fst, src/checker/Pulse.Typing.LN.fst, src/checker/Pulse.Typing.Printer.fst, src/ocaml/plugin/generated/Pulse_Checker_Prover_Substs.ml, src/ocaml/plugin/generated/Pulse_Checker_Pure.ml, src/ocaml/plugin/generated/Pulse_Typing_Combinators.ml
Nothing really visible to users. This PR is mostly to make a subsequent one smaller.
=> Misc changes

CONTRIBUTING.md
This is a trivial documentation change -- I just noticed the explanation of KRML_HOME was missing while getting the project to compile.
ping @tahina-pro
=> doc: building: mention KRML_HOME environment variable

.devcontainer/fromscratch/devcontainer.json, .devcontainer/fromscratch/minimal.Dockerfile, .devcontainer/rebuild-container-and-deploy.sh
This adds a new devcontainer that starts from a cached docker container (from dockerhub) and a script to update it. It's under my username for now.. but we can change that.
This devcontainer only installs dependencies, and does not build pulse itself. See https://github.com/FStarLang/pulse-sandbox for a devcontainer that quickly sets up a Pulse environment.
=> Add a cached devcontainer and update script

src/checker/Pulse.Checker.Prover.IntroExists.fst, src/checker/Pulse.Syntax.Base.fsti, src/ocaml/plugin/generated/Pulse_Checker_Prover_IntroExists.ml, src/ocaml/plugin/generated/Pulse_Syntax_Base.ml
Example:
assume val f : int -> vprop
```pulse
fn foo ()
requires exists* x. f x
ensures  emp
{
admit()
}
```
```pulse
fn test (x:int)
requires emp
ensures  emp
{
foo ()
}
```
Before:
```
- Cannot prove:
f x
- In the context:
emp
```
After:
```
- Cannot prove:
f ?x
- In the context:
emp
```
I think this is clearer, since otherwise it looks like the `x` in scope.
=> Give a name starting with '?' to uvars introduced by the Pulse checker

src/checker/Pulse.Typing.FV.fst, src/ocaml/plugin/FStar_Parser_Parse.mly, src/ocaml/plugin/generated/Pulse_Typing_FV.ml
This proof was way too large and brittle for the SMT. Split it into cases, in separate functions, which makes it robust.
=> Tame Pulse.Typing.FV

src/checker/Pulse.Checker.Admit.fst, src/checker/Pulse.Checker.AssertWithBinders.fst, src/checker/Pulse.Checker.Prover.fst, src/checker/Pulse.Checker.VPropEquiv.fsti, src/checker/Pulse.Syntax.Naming.fst, src/checker/Pulse.Syntax.Printer.fst, src/checker/Pulse.Syntax.Pure.fst, src/checker/Pulse.Typing.Combinators.fsti, src/ocaml/plugin/generated/Pulse_Checker_Admit.ml, src/ocaml/plugin/generated/Pulse_Checker_AssertWithBinders.ml, src/ocaml/plugin/generated/Pulse_Checker_Exists.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_Base.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_ElimExists.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_ElimPure.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_IntroExists.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_IntroPure.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_Match.ml, src/ocaml/plugin/generated/Pulse_Checker_VPropEquiv.ml, src/ocaml/plugin/generated/Pulse_Syntax_Printer.ml, src/ocaml/plugin/generated/Pulse_Syntax_Pure.ml, src/ocaml/plugin/generated/Pulse_Typing_Combinators.ml
1- make sure to print one resource per line (unless they all fit in a single line)
2- sort the resources (only at the top level! arguments to combinators will _not_ be sorted) to bring similar things together
The example from #96 goes from
```
- Current context:
gpu_pts_to_array gr (reveal s) **
cpu **
A.pts_to a2 (reveal s) **
gpu_pts_to_array ga2 (reveal s) **
pts_to i (reveal v) **
A.pts_to ar (Seq.Base.create (SZ.v (SZ.uint_to_t size)) 0) **
A.pts_to a1 (reveal s) ** gpu_pts_to_array ga1 (reveal s)
```
to
```
- Current context:
cpu **
A.pts_to a1 (reveal s) **
A.pts_to a2 (reveal s) **
A.pts_to ar (Seq.Base.create (SZ.v (SZ.uint_to_t size)) 0) **
pts_to i (reveal v) **
gpu_pts_to_array ga1 (reveal s) **
gpu_pts_to_array ga2 (reveal s) **
gpu_pts_to_array gr (reveal s)
```
Fixes #96
=> Printing improvements

lib/pulse/core/PulseCore.FractionalPermission.fst
(this depends on https://github.com/FStarLang/FStar/pull/3305 to make sense)
This enables simplification rules (from
https://github.com/FStarLang/FStar/pull/3305) to kick in, and potentially significantly reduce the number of queries we send to the SMT. For instance, for DPE.fst:
Before (595 total queries):
Verified module: DPE
All verification conditions discharged successfully
ramon: end                  Thu May 23 10:25:28 2024
ramon: root.execname        fstar.exe
ramon: root.utime           12.940s
ramon: root.stime           0.160s
ramon: group.total          139.763s
ramon: group.utime          139.459s
ramon: group.stime          0.304s
ramon: group.mempeak        2181MiB
ramon: group.pidpeak        4
ramon: status               exited
ramon: exitcode             0
ramon: walltime …
=> FractionalPermission: use a literal 0.0R

share/pulse/examples/bug-reports/Bug100.fst, share/pulse/examples/bug-reports/Bug59.fst, share/pulse/examples/by-example/PulseTutorial.AtomicsAndInvariants.fst, src/checker/Pulse.Main.fst, src/ocaml/plugin/generated/Pulse_Main.ml
I think this will be a lot more predictable, and it's an easy change. The old behavior can be recovered with:
```
#set-options "--ext pulse:guard_policy=SMT"
```
=> Setting guard policy to ForceSMT by default

lib/pulse/lib/Pulse.Lib.Reference.fst, lib/pulse/lib/Pulse.Lib.Reference.fsti, share/pulse/examples/Val.fst, share/pulse/examples/Val.fsti, src/Makefile, src/checker/Pulse.Checker.Admit.fst, src/checker/Pulse.Main.fst, src/checker/Pulse.Recursion.fst, src/checker/Pulse.Recursion.fsti, src/checker/Pulse.RuntimeUtils.fsti, src/checker/Pulse.Syntax.Base.fsti, src/checker/Pulse.Syntax.Builder.fst, src/checker/Pulse.Syntax.Printer.fst, src/ocaml/plugin/PulseSyntaxExtension_SyntaxWrapper.ml, src/ocaml/plugin/Pulse_RuntimeUtils.ml, src/ocaml/plugin/generated/PulseSyntaxExtension_Desugar.ml, src/ocaml/plugin/generated/PulseSyntaxExtension_Sugar.ml, src/ocaml/plugin/generated/Pulse_Checker_Admit.ml, src/ocaml/plugin/generated/Pulse_Main.ml, src/ocaml/plugin/generated/Pulse_Recursion.ml, src/ocaml/plugin/generated/Pulse_Syntax_Base.ml, src/ocaml/plugin/generated/Pulse_Syntax_Builder.ml, src/ocaml/plugin/generated/Pulse_Syntax_Printer.ml, src/ocaml/plugin/pulseparser.mly, src/syntax_extension/PulseSyntaxExtension.Desugar.fst, src/syntax_extension/PulseSyntaxExtension.Sugar.fst, src/syntax_extension/PulseSyntaxExtension.SyntaxWrapper.fsti
After some fixes in F* (FStarLang/FStar#3329) this now works more reliably.
~~There is one giant problem still, which is that the check for all vals being defined is done during interleaving, and at that time there are no vals for the Pulse definitions (they are just syntax extension blobs) so we never report an error if we forgot to define something (or made a typo in the name). I think we can fix this in F* by keeping track of yet-undefined vals in the typechecker.~~ Fixed by https://github.com/FStarLang/FStar/pull/3330
Also, the syntax blobs don't really have a name, so they do not get interleaved properly.
=> Support for val declarations (in Pulse syntax)

share/pulse/examples/bug-reports/Bug34.fst, src/checker/Pulse.Checker.Abs.fst, src/checker/Pulse.Elaborate.Pure.fst, src/checker/Pulse.Syntax.Base.fsti, src/checker/Pulse.Syntax.Printer.fst, src/checker/Pulse.Typing.LN.fst, src/ocaml/plugin/PulseSyntaxExtension_SyntaxWrapper.ml, src/ocaml/plugin/generated/PulseSyntaxExtension_Desugar.ml, src/ocaml/plugin/generated/Pulse_Checker_Abs.ml, src/ocaml/plugin/generated/Pulse_Elaborate_Pure.ml, src/ocaml/plugin/generated/Pulse_Syntax_Base.ml, src/ocaml/plugin/generated/Pulse_Syntax_Printer.ml, src/syntax_extension/PulseSyntaxExtension.Desugar.fst, src/syntax_extension/PulseSyntaxExtension.SyntaxWrapper.fsti
While the plan is to just move to F* binders, this patch was pretty easy
and already allows us to use typeclass in Pulse code.
Fixes https://github.com/FStarLang/pulse/issues/34
=> Syntax/Checker: support typeclass arguments

lib/pulse/lib/Pulse.Lib.Codeable.fsti, src/checker/Pulse.Checker.Prover.ElimExists.fst, src/checker/Pulse.Checker.Prover.Explode.fst, src/checker/Pulse.Checker.Prover.fst, src/ocaml/plugin/generated/Pulse_Checker_Prover.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_ElimExists.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_Explode.ml
Now all passes are just registered into a list, which makes it easy to extend them.
```fstar
res_advance <| prover_iteration_loop pst [
// P "elim_pure_pst"     ElimPure.elim_pure_pst;
P "elim_exists"       ElimExists.elim_exists_pst;
P "collect_exists"    prover_pass_collect_exists;
P "explode"           Explode.explode;
P "match_syntactic"   Match.match_syntactic;
P "match_fastunif"    Match.match_fastunif;
P "match_fastunif_i"  Match.match_fastunif_i;
P "match_full"        Match.match_full;
]
```
=> Some refactor in the prover

src/Makefile, src/extraction/Extraction.fst.config.json
- Fix `make boot-checker` rule to also bootstrap extraction
- Fix config.json file (was missing src/data from F*)
=> Extraction nits

src/extraction/ExtractPulse.fst, src/ocaml/plugin/generated/ExtractPulse.ml
I noticed `(!)` and `(:=)` fail to extract for Box. I think the idea is turn them into references and use the reference ops, but these are still there and usable in the module. If they are, they should probably extract like this?
Or, we can remove them too.
=> ExtractPulse.fst: support read/write for Box

lib/pulse/lib/Pulse.Lib.CancellableInvariant.fst, lib/pulse/lib/Pulse.Lib.ConditionVarWithCodes.fst, lib/pulse/lib/Pulse.Lib.FlippableInv.fst, lib/pulse/lib/Pulse.Lib.SpinLock.fst, lib/pulse/lib/Pulse.Lib.SpinLockToken.fst, lib/pulse/lib/pledge/Pulse.Lib.InvList.fst, share/pulse/examples/Invariant.fst, share/pulse/examples/PulseCorePaper.S2.Lock.fst, share/pulse/examples/bug-reports/Bug.Invariants.fst, share/pulse/examples/by-example/ParallelIncrement.fst, share/pulse/examples/by-example/PulseTutorial.ParallelIncrement.fst, share/pulse/examples/by-example/PulseTutorial.SpinLock.fst, src/checker/Pulse.Checker.Base.fsti, src/checker/Pulse.Checker.WithInv.fst, src/ocaml/plugin/generated/Pulse_Checker_WithInv.ml
The PR fixes the pulse checker so that the with_invariants ensures can be annotated just as p * frame, as opposed to inv i p * frame.
=> Fix ensures annotations on with_invariants

lib/pulse/lib/Pulse.Lib.Core.fst, lib/pulse/lib/Pulse.Lib.Core.fsti, share/pulse/examples/Unfold.fst, src/checker/Pulse.Checker.Prover.fst, src/ocaml/plugin/generated/Pulse_Checker_Prover.ml
Cf #142 .
If we want to use F*'s `unfold`, we can, but we need to expose a `norm_step` in Pervasives to allow tactics to select the `Unfold_for_unification_and_vcgen` normalizer flag.
cc @nikswamy
=> Adding a pulse_unfold attribute to eagerly unfold slprops in ctx/goal

share/pulse/examples/Invariant.fst, src/checker/Pulse.Checker.WithInv.fst, src/ocaml/plugin/generated/Pulse_Checker_WithInv.ml
Prompted by Nik noticing we are not unfolding resources when checking a with_invariants block, where we need to find the resource associated with the invariant.
It is not kicking in by default since normalization of the context and goals happens only in the _prover_, not at every iteration of the _checker_. Maybe it should?
=> Normalize context for with_inv detection

Pulse.fst.config.json, lib/pulse/lib/Pulse.Lib.SpinLock.fst, lib/pulse/lib/Pulse.Lib.WhileLoop.fst, share/pulse/examples/MatchRW.fst, share/pulse/examples/Unfold.fst, share/pulse/examples/by-example/ParallelIncrement.fst, share/pulse/examples/by-example/PulseTutorial.Conditionals.fst, share/pulse/examples/by-example/PulseTutorial.ParallelIncrement.fst, share/pulse/examples/dice/dpe/DPE.fst, share/pulse/examples/dice/dpe/DPETypes.fsti, src/checker/Pulse.Checker.If.fst, src/checker/Pulse.Checker.Match.fst, src/ocaml/plugin/generated/Pulse_Checker_If.ml, src/ocaml/plugin/generated/Pulse_Checker_Match.ml
A very common step after a `match e { Foo a1 .. an -> { .. } }` is to rewrite `e` in the context to `Foo a1 .. an`. This patch makes this happen automatically.
This is not exactly backwards compatible, see for instance the patches to PulseTutorial.Conditionals. For DPE, I tweaked some rewrite lemmas which seemed to be working around the fact that the context is not automatically rewritten, I think it's a bit simpler now.
If the behavior seems fine I can probably simplify some more code.
=> Rewriting the scrutinee in the branches of a match

lib/pulse/lib/Pulse.Lib.Stick.fst, lib/pulse/lib/pledge/Pulse.Lib.Pledge.fst, lib/pulse/lib/pledge/Pulse.Lib.Pledge.fsti, lib/pulse/lib/pledge/Pulse.Lib.SmallTrade.fst, lib/pulse/lib/pledge/Pulse.Lib.SmallTrade.fsti, lib/pulse/lib/pledge/Pulse.Lib.Trade.fst, lib/pulse/lib/pledge/Pulse.Lib.Trade.fsti, share/pulse/examples/PledgeArith.fst, share/pulse/examples/Quicksort.Task.fst, share/pulse/examples/parix/ParallelFor.fst, share/pulse/examples/parix/Promises.Examples3.fst
Keeping the module for posterity, but not depending on it
=> Lib: removing uses of InvList

lib/pulse/lib/Pulse.Lib.HashTable.fst, lib/pulse/lib/Pulse.Lib.HashTable.fsti, pulse2rust/dpe/src/generated/dpe.rs, pulse2rust/dpe/src/generated/pulse_lib_hashtable.rs, share/pulse/examples/dice/dpe/DPE.fst
Internally, the hash table performs an addition of two SZ.t, which are then taken modulo the size of the table. Since the addition can overflow, the hash table was dynamically checking for an overflow (by checking that it the addition wouldn't surpass 0xffff, a lower bound for a max SZ.t) and handling overflows by returning an error code.
That is of course not ideal, especially since said overflows could really just be impossible (e.g. on a table of size 256).
This patch changes the interface to only allow creating tables with a size `l` such that `2*l` fits in a SZ.t, which prevents any possible overflow. With the SizeT module as it is now this means we can always create tables up to size 0x7fff, and larger ones by assuming `fits_u32` or `fits_u64`.
This simplifies the code somewhat too. …
=> Pulse.Lib.HashTable: prevent internal overflows by bounding size

share/pulse/examples/bug-reports/error-messages/Bug.DesugaringError.fst, share/pulse/examples/bug-reports/error-messages/Bug.DesugaringError.fst.expected, src/checker/Pulse.Checker.Pure.fst, src/checker/Pulse.Main.fst, src/checker/Pulse.RuntimeUtils.fsti, src/checker/Pulse.Syntax.Naming.fst, src/checker/Pulse.Syntax.Naming.fsti, src/ocaml/plugin/PulseSyntaxExtension_SyntaxWrapper.ml, src/ocaml/plugin/Pulse_RuntimeUtils.ml, src/ocaml/plugin/generated/PulseSyntaxExtension_Desugar.ml, src/ocaml/plugin/generated/Pulse_Checker_Pure.ml, src/ocaml/plugin/generated/Pulse_Main.ml, src/ocaml/plugin/generated/Pulse_Syntax_Naming.ml, src/syntax_extension/PulseSyntaxExtension.Desugar.fst, src/syntax_extension/PulseSyntaxExtension.SyntaxWrapper.fsti
PulseSyntaxExtension.Desugar: Was missing an closing substitution on the binders of FnDefn/FnDecl
Pulse.Syntax.Naming: Map opening substitutions to FStar.Syntax.Syntax.DB substitutions to preserve ranges
Previously:
```
let id (#a:Type) (x y:a) = x
[@@expect_failure]
fn test3 (x:nat) (y:bool)
requires emp
returns z:nat
ensures emp
{
id x y
}
```
This would report a typing error on `y`, but it would point to the binder `y:bool`.
Now, it correctly points to the usage site.
=> Missing closing substitution in desugar; fix ranges when opening a variable

src/checker/Pulse.Typing.Env.fst, src/ocaml/plugin/generated/Pulse_Typing_Env.ml
Now that we have fail_at from Nik, we can localize the "Pulse
checker failed" error instead of highlighting a huge range.
=> Fail with a proper range

src/checker/Pulse.Checker.Bind.fst, src/checker/Pulse.Checker.fst, src/ocaml/plugin/generated/Pulse_Checker.ml, src/ocaml/plugin/generated/Pulse_Checker_Bind.ml
This is not polished at all, but I find it quite useful already.
=> Introduce --ext 'pulse:trace' to print contexts before every step

src/ocaml/plugin/Pulse_Extract_CompilerLib.ml
See https://github.com/FStarLang/karamel/issues/478. Revert until it is fixed, and we should add an option anyway.
This reverts commit 3a7730d98b619449e228c99fd33872042c3f666f.
=> Revert "Extraction: mark everything CInline"

share/pulse/examples/bug-reports/error-messages/Bug.DesugaringError.fst.expected, src/checker/Pulse.Checker.fst, src/checker/Pulse.RuntimeUtils.fsti, src/ocaml/plugin/Pulse_RuntimeUtils.ml, src/ocaml/plugin/generated/Pulse_Checker.ml
This PR prevents error reporting from highlighting an entire decl or reporting problems in another file by using F*'s error bound feature (https://github.com/FStarLang/FStar/pull/3487). The checker will now set the error bound to the st_term being checked, so no errors can escape it.
=> Setting the error bound

pulse2rust/Makefile, pulse2rust/dpe/src/generated/dpe.rs, pulse2rust/dpe/src/generated/evercrypt_gen.rs, pulse2rust/src/Pulse2Rust.Extract.fst, pulse2rust/src/Pulse2Rust.Rust.Syntax.fst, pulse2rust/src/Pulse2Rust.Rust.Syntax.fsti, pulse2rust/src/Pulse2Rust.fst, pulse2rust/src/ocaml/.gitignore, pulse2rust/src/ocaml/Cargo.toml, pulse2rust/src/ocaml/dune, pulse2rust/src/ocaml/generated/Pulse2Rust.ml, pulse2rust/src/ocaml/generated/Pulse2Rust_Extract.ml, pulse2rust/src/ocaml/generated/Pulse2Rust_Rust_Syntax.ml, pulse2rust/src/ocaml/rust/src/lib.rs
Various updates to pulse2rust.  Newly supported functions:
- bit operations (shifts, or, and)
- `x._1`
- `FStar.Int.Cast.*`
- `pts_to_range_index`
Also fixes #219.  Thanks to @aseemr for pointing me in the right direction!
=> Support more pulse in pulse2rust

share/pulse/examples/Test.GenOrder.fst, src/ocaml/plugin/generated/PulseSyntaxExtension_Env.ml, src/syntax_extension/PulseSyntaxExtension.Env.fst
Arguments for ticked variables were not necessarily in textual order, due to the deduplication being right-biased. This PR fixes it so
```
fn flip ()
requires foo 'x 'y
ensures  foo 'y 'x
{ admit(); }
fn test ()
requires foo 1 2
ensures  foo 2 1
{
flip () #1 #2;
}
```
now works, since the arguments are `(#x #y : _)` instead of `(#y #x : _)`.
=> Tick order

share/pulse/examples/Test.GenOrder2.A.fsti, share/pulse/examples/Test.GenOrder2.B.fst, src/ocaml/plugin/generated/PulseSyntaxExtension_Desugar.ml, src/syntax_extension/PulseSyntaxExtension.Desugar.fst
=> SyntaxExtension: handle ticks in declarations

lib/pulse/lib/Pulse.Lib.Box.fst, lib/pulse/lib/Pulse.Lib.Box.fsti, lib/pulse/lib/Pulse.Lib.Primitives.fst, src/ci/ci.Dockerfile, src/ci/hierarchic.Dockerfile
This improves typechecking slightly since we know `box` is fresh. Also, if we happen to `friend` this module, typeclass resolution will not confuse the instances for references and boxes.
=> Box: use a newtype in the model

share/pulse/examples/bug-reports/Bug234.fst, src/checker/Pulse.Checker.Base.fst, src/checker/Pulse.Checker.Exists.fst, src/checker/Pulse.Checker.STApp.fst, src/checker/Pulse.Checker.While.fst, src/checker/Pulse.RuntimeUtils.fsti, src/checker/Pulse.Typing.Combinators.fst, src/checker/Pulse.Typing.Combinators.fsti, src/checker/Pulse.Typing.Env.fst, src/checker/Pulse.Typing.Env.fsti, src/checker/Pulse.Typing.Metatheory.Base.fst, src/checker/Pulse.Typing.Metatheory.Base.fsti, src/checker/Pulse.Typing.Metatheory.fst, src/checker/Pulse.Typing.Metatheory.fsti, src/ocaml/plugin/Pulse_RuntimeUtils.ml, src/ocaml/plugin/generated/Pulse_Checker.ml, src/ocaml/plugin/generated/Pulse_Checker_Base.ml, src/ocaml/plugin/generated/Pulse_Checker_Exists.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover.ml, src/ocaml/plugin/generated/Pulse_Checker_Prover_ElimExists.ml, src/ocaml/plugin/generated/Pulse_Checker_Pure.ml, src/ocaml/plugin/generated/Pulse_Checker_STApp.ml, src/ocaml/plugin/generated/Pulse_Extract_Main.ml, src/ocaml/plugin/generated/Pulse_Typing_Combinators.ml, src/ocaml/plugin/generated/Pulse_Typing_Env.ml, src/ocaml/plugin/generated/Pulse_Typing_Metatheory_Base.ml
In Pulse, we create free variables to open terms (mainly to check abs terms) and then expect to be able to call F* on those opened terms containing free variables created in Pulse (to normalize, to check equivalence, and to check typing).  For this to work, F* must not create variables that clash with Pulse's.  (Otherwise the names can clash and we get bugs like #234.)
This PR changes the `fresh` function in `Pulse.Typing.Env` to use the F* gensym.
The typing of `fresh` is a bit questionable now.  It promises to return a variable not present in the Pulse environment but that will only be true if all variables were created with `fresh`.  But I suspect that the reflection API requires changes to address the name clash issue (e.g. equiv tokens probably allow you to derive false from a name …
=> Use gensym from F*

lib/pulse/lib/Pulse.Lib.Slice.Util.fst
The RHS of the trade should be the same as the precondition of the function.
=> Fix postcondition of `Pulse.Lib.Slice.Util.split_trade`

lib/pulse/lib/Pulse.Lib.ArrayPtr.fst, lib/pulse/lib/Pulse.Lib.ArrayPtr.fsti, lib/pulse/lib/Pulse.Lib.Slice.Util.fst, lib/pulse/lib/Pulse.Lib.Slice.fst, lib/pulse/lib/Pulse.Lib.Slice.fsti, pulse2rust/src/Pulse2Rust.Extract.fst, pulse2rust/src/Pulse2Rust.Rust.Syntax.fst, pulse2rust/src/Pulse2Rust.Rust.Syntax.fsti, pulse2rust/src/ocaml/generated/Pulse2Rust_Extract.ml, pulse2rust/src/ocaml/generated/Pulse2Rust_Rust_Syntax.ml, pulse2rust/src/ocaml/rust/src/lib.rs, pulse2rust/tests/src/example_slice.rs, share/pulse/examples/Example.Slice.fst, src/extraction/ExtractPulse.fst, src/ocaml/plugin/generated/ExtractPulse.ml
This extends the new slice API with a new `subslice` function extracting to `&s[a..b]` in Rust.
=> Slice.subslice

lib/pulse/lib/Pulse.Lib.Slice.Util.fst, src/checker/Pulse.Extract.CompilerLib.fsti, src/checker/Pulse.Extract.Main.fst, src/ocaml/plugin/Pulse_Extract_CompilerLib.ml, src/ocaml/plugin/generated/Pulse_Extract_Main.ml
Inner ghost functions used to be extracted as `Obj.magic (fun _ -> ())` (that's the definition, not the call site).  Changing the let to have a pure effect allows extraction to remove the definition and the associated magic (which in turn breaks pulse2rust).
More generally, I'm not sure if we need to put a DIV-effect on let-bindings with a C_Tot effect at all.
=> Correctly extract inner ghost functions.

lib/pulse/lib/Pulse.Lib.SeqMatch.Util.fst, lib/pulse/lib/pledge/Pulse.Lib.Trade.Util.fst
Pulse.Lib.Trade.Util now follows a pattern similar to Pulse.Lib.Stick.Util, with the trade replacing the stick.
=> Extra lemmas about SeqMatch, Trade

lib/pulse/lib/Pulse.Lib.Array.MergeSort.fst
This may be inefficient due to the large number of array swaps, and stack space O(log n); but no heap allocation.
=> In-place array merge sort

lib/pulse/lib/Pulse.Lib.Slice.Util.fst, lib/pulse/lib/Pulse.Lib.Slice.fst, lib/pulse/lib/Pulse.Lib.Slice.fsti, pulse2rust/src/Pulse2Rust.Extract.fst, pulse2rust/src/ocaml/generated/Pulse2Rust_Extract.ml, share/pulse/examples/Example.Slice.fst
The ongoing extension of Karamel by @msprotz and @R1kM to support extraction to Rust stumbles on the `slice_pair` type, which foils mutability analysis: the same type cannot be used to represent both mutable and immutable slice pairs.
Instead, Jonathan proposes to retire this type in favor of using standard F* pairs, which Karamel would then extract to standard Rust pairs with proper mutability per use.
=> Remove `slice_pair` in favor of standard F* pairs

lib/pulse/lib/Pulse.Lib.SeqMatch.fst, lib/pulse/lib/Pulse.Lib.SeqMatch.fsti, lib/pulse/lib/Pulse.Lib.Stick.Util.fst
This PR gives a `.fst` implementation for `Pulse.Lib.SeqMatch.fsti`
It is inspired from the existing Steel implementation (cf. https://github.com/FStarLang/steel/blob/92f1f3761373d1c4b8ee91f12bec007515dfce1d/lib/steel/Steel.ST.SeqMatch.fst ), but is tidied up to avoid resource leakage by no longer using `drop`.
With this PR, the following changes in the interface have become necessary:
* We lose universe polymorphism. This PR sets everything to universe 0.
* `seq_list_match_nil_elim` is strengthened by weakening its precondition
* to avoid resource leakage, `seq_seq_match_item_match_option_upd` is split into a `_none` and a `_some` cases.
=> Implement Pulse.Lib.SeqMatch

lib/pulse/core/PulseCore.Action.fst, lib/pulse/core/PulseCore.IndirectionTheoryActions.fst, lib/pulse/core/PulseCore.IndirectionTheoryActions.fsti, lib/pulse/core/PulseCore.IndirectionTheorySep.fsti, lib/pulse/core/PulseCore.InstantiatedSemantics.fst, lib/pulse/core/PulseCore.PotentiallyErased.fst, lib/pulse/core/PulseCore.PotentiallyErased.fsti, lib/pulse/core/PulseCore.Semantics.fst
Adds a type `PotentiallyErased.erased t` for values that might be erased depending on the (opaque) implementation of `PotentiallyErased`.  Parametricity then guarantees that the nonerased version refines the erased one.
We use this new type to track the fuel of a memory, which is defined as `level m - credits m`.
=> Keep track of a potentially erased fuel quantity.

lib/pulse/lib/Pulse.Lib.Slice.Util.fst, lib/pulse/lib/Pulse.Lib.Slice.fst, lib/pulse/lib/Pulse.Lib.Slice.fsti
This is only for reasoning purposes, in the sense that, contrary to arrays or array pointers, when ghost-splitting a slice, the two subslices are returned erased, and there is no way to get a non-erased hold on them.
=> Add ghost slice splitting

lib/pulse/lib/Pulse.Lib.Slice.Util.fst, lib/pulse/lib/Pulse.Lib.Slice.fst, lib/pulse/lib/Pulse.Lib.Slice.fsti
This PR adds a few functions to convert from Pulse.Lib.Slice.slice to Pulse.Lib.ArrayPtr.ptr and conversely: `slice_to_arrayptr_intro`, `elim`, and `arrayptr_to_slice_intro`, `elim`
**Any Pulse code making use of these functions is supposed to be extracted to C only. These functions WILL NOT extract to Rust.**
The purpose of these functions is to avoid having slices as arguments or return values of functions in a C API. This is helpful to avoid double definitions of types due to Karamel monomorphizations when separately extracting a library and an application.
=> Convert slices to/from ArrayPtr (C only)

lib/pulse/lib/Pulse.Lib.HashTable.Spec.fst
This is a weird one:
- It only fails on my laptop (which is aarch64), and
- it only fails on the command-line (but vscode is fine).
=> Increase rlimit.

test/bug-reports/error-messages/Makefile
Following F* tests/error_messages
=> --ext fstar:no_absolute_paths in tests/error_messages

src/ml/PulseSyntaxExtension_Parser.ml, src/syntax_extension/PulseSyntaxExtension.ASTBuilder.fst, src/syntax_extension/PulseSyntaxExtension.Desugar.fsti, src/syntax_extension/PulseSyntaxExtension.Err.fst, src/syntax_extension/PulseSyntaxExtension.Parser.fsti
Needed after https://github.com/FStarLang/FStar/pull/3763, and an improvement in the reporting of syntax errors (whitespace is no longer messed up).
=> Parser: Use structured errors

lib/pulse/lib/Pulse.Lib.CancellableInvariant.fst, share/pulse/examples/by-example/PulseTutorial.ParallelIncrement.fst, src/ml/FStarC_Parser_Parse.mly, src/ml/pulseparser.mly, src/syntax_extension/PulseSyntaxExtension.Desugar.fst, src/syntax_extension/PulseSyntaxExtension.Env.fst, src/syntax_extension/PulseSyntaxExtension.Sugar.fst, test/nolib/Annots.fst, test/nolib/Annots.fst.output.expected
This makes the parser just parse a list (any list) of annotations (requires, ensures, returns, opens) for computation types, and it's the desugaring that checks for their ordering, does defaulting when one is not present, and even combines multiples requires/ensures.
This allows things like:
```fstar
fn foo1 ()
{ (); }
fn foo2 ()
returns int
{ 1 }
fn foo2' ()
returns _ : int
{ 1 }
fn multiple_req ()
requires res 1
requires res 2
ensures res 2 ** res 1
{ () }
```
And makes sure to forbid wrongly ordered annotations, or multiple returns/opens. It also makes sure opens comes before returns, since the name returned in *not* in scope for the opens, and our current syntax is very misleading in that aspect.
=> Parsing: relax ordering/need for annotations in computation types

lib/pulse/lib/Pulse.Lib.Deque.fst, lib/pulse/lib/Pulse.Lib.Task.fst, share/pulse/examples/by-example/PulseTutorial.PCMParallelIncrement.fst, src/checker/Pulse.Checker.AssertWithBinders.fst, src/checker/Pulse.Checker.Prover.fst, src/checker/Pulse.Checker.Prover.fsti
If a rewrite each doesn't do anything, it is silently accepted. This will make it raise a warning.
=> Checker.Rewrite: warn if a rewrite each was a no-op

src/checker/Pulse.Checker.Prover.fst, test/nolib/UnfoldFst.fst
I added this but we are not relying on it, and it can be counterproductive as the example shows. This came up in the CBOR branch of everparse.
=> Not unfolding fst/snd/dfst/dsnd

lib/pulse/lib/Pulse.Lib.ArrayPtr.fst, lib/pulse/lib/Pulse.Lib.ArrayPtr.fsti, lib/pulse/lib/Pulse.Lib.Slice.Util.fst, lib/pulse/lib/Pulse.Lib.Slice.fst, lib/pulse/lib/Pulse.Lib.Slice.fsti, test/Example.Slice.fst
cc @tahina-pro, this allows to not necessarily use the typeclass when using these predicates which is useful to disambiguate. They will automatically unfold and the context will now show the concrete `pts_to`, which I think is desirable
=> ArrayPtr/Slice: expose pts_to, make instance transparent

lib/common/Pulse.Lib.Core.fsti, lib/core/Pulse.Lib.Core.fst, lib/core/PulseCore.Action.fst, lib/core/PulseCore.Action.fsti, lib/core/PulseCore.Atomic.fst, lib/core/PulseCore.Atomic.fsti, lib/core/PulseCore.IndirectionTheoryActions.fst, lib/core/PulseCore.IndirectionTheoryActions.fsti, lib/core/PulseCore.IndirectionTheorySep.fst, lib/core/PulseCore.IndirectionTheorySep.fsti, lib/core/PulseCore.InstantiatedSemantics.fst, lib/core/PulseCore.InstantiatedSemantics.fsti, lib/core/PulseCore.KnotInstantiation.fsti
The only unexpected change is that `later_exists` no longer holds; you cannot commute existentials and later equationally.  You can still turn `later (exists* x. f x)` into `exists* x. later (f x)` using a ghost action though.
=> Use Iris definition of later and prove Löb induction

lib/pulse/lib/Pulse.Lib.AVLTree.fst, src/checker/Pulse.Checker.Match.fst, src/checker/Pulse.Extract.Main.fst, src/checker/Pulse.Simplify.fst, src/checker/Pulse.Soundness.Match.fst, src/checker/Pulse.Syntax.Base.fst, src/checker/Pulse.Syntax.Base.fsti, src/checker/Pulse.Syntax.Builder.fst, src/checker/Pulse.Syntax.Naming.fsti, src/checker/Pulse.Syntax.Printer.fst, src/checker/Pulse.Typing.FV.fst, src/checker/Pulse.Typing.LN.fst, src/checker/Pulse.Typing.fst, src/ml/PulseSyntaxExtension_Parser.ml, src/ml/PulseSyntaxExtension_SyntaxWrapper.ml, src/ml/pulseparser.mly, src/syntax_extension/PulseSyntaxExtension.Desugar.fst, src/syntax_extension/PulseSyntaxExtension.Sugar.fst, src/syntax_extension/PulseSyntaxExtension.SyntaxWrapper.fsti, src/syntax_extension/PulseSyntaxExtension.TransformRValues.fst, test/bug-reports/Bug94.fst.output.expected, test/nolib/Bug357.fst, test/nolib/NoRewrite.fst
- allowing to avoid autorewrite in matches
- Make autorewrite work for let <pattern> = foo
=> Fixes for autorewrite in matches/let

src/syntax_extension/PulseSyntaxExtension.Desugar.fst, test/LocalFnAnnot.fst
```fstar
let t (p: slprop) = unit -> stt unit (requires p) (ensures fun _ -> emp)
fn f (p: slprop) requires p {
fn g p : t p = a { drop_ p; };
g p ()
}
```
=> Support type annotations on local functions.

src/checker/Pulse.Checker.STApp.fst, src/checker/Pulse.Show.fst, src/checker/Pulse.Show.fsti, src/checker/Pulse.Syntax.Pure.fst, test/nolib/Implicits.fst
We're still not automatically instantiating meta args (including typeclass) at the end of an STApp. See the added test for some calls that fail, but would be nice to have.
=> Recognizing meta qualifiers more, allowing to instantiate a final argument

lib/pulse/lib/Pulse.Lib.AVLTree.fst, lib/pulse/lib/Pulse.Lib.Box.fst, lib/pulse/lib/Pulse.Lib.LinkedList.fst, lib/pulse/lib/Pulse.Lib.Task.fst, lib/pulse/lib/Pulse.Lib.Vec.fst, lib/pulse/lib/Pulse.Lib.Vec.fsti, share/pulse/examples/GhostStateMachine.fst, share/pulse/examples/Invariant.fst, share/pulse/examples/ZetaHashAccumulator.fst, test/Test.ReflikeClass.fst, test/bug-reports/Records.fst
This removes tons of warnings about Reference.alloc (and others) being deprecated. It mostly uniformly moves everything to boxes and vectors.
=> Removing uses of internal ref/array allocs, use box/vec instead

lib/pulse/lib/Pulse.Lib.HashTable.fst, src/checker/Pulse.Checker.Prover.Match.MKeys.fst, src/checker/Pulse.Checker.Prover.Match.MKeys.fsti, src/checker/Pulse.Checker.Prover.Match.Matchers.fst, src/checker/Pulse.Checker.Prover.fst, src/checker/Pulse.Checker.Rewrite.fst, src/checker/Pulse.Soundness.SLPropEquiv.fst, src/checker/Pulse.Typing.fst, src/checker/Pulse.VC.fst, src/checker/Pulse.VC.fsti, test/Test.Basic1.fst
This PR prevents the use of SMT for typechecking the solutions of solved uvars, which can have a huge impact. This actually makes the internal much simpler. I've seen 5x improvements with this patch, I'd like to test it more though as it did break a few of my proofs.
@tahina-pro maybe give it a spin in everparse?
=> Yet more matching improvements

lib/common/Pulse.Lib.Core.fsti, lib/core/Pulse.Lib.Core.fst, lib/core/PulseCore.Action.fst, lib/core/PulseCore.Action.fsti, lib/core/PulseCore.Atomic.fst, lib/core/PulseCore.Atomic.fsti, lib/pulse/lib/Pulse.Lib.Task.fst, lib/pulse/lib/pledge/Pulse.Lib.Shift.fst, lib/pulse/lib/pledge/Pulse.Lib.Trade.fst
Currently we can only lift an `stt_atomic a ...` to `stt a ...` if `a` lives in a universe less than 100; even more restrictively, we only expose functions `lift_atomic0` through `lift_atomic3`.  The reason for this restriction is that we need to specify a maximum universe for actions in the stt tree; and we arbitrarily set this limit to 100.
This PR lifts this restriction by redefining `stt_atomic a ...` to be, roughly, a triple:
- a small type in Type u#5
- an action producing a value in this small type
- and a total function mapping the value produced by the action to a value in `a`
The actions stored in the stt tree now always produce values in universe 5, solving the issue.
The only downside is that `stt_atomic` and `stt_ghost` now live in universe 5 instead of 4.  Not that it …
=> Lift stt_atomic to stt in all universes.

lib/common/Pulse.Lib.Core.fsti, src/checker/Pulse.Checker.AssertWithBinders.fst, src/checker/Pulse.Checker.Rewrite.fst, src/checker/Pulse.Reflection.Util.fst, src/checker/Pulse.RuntimeUtils.fsti, src/ml/Pulse_RuntimeUtils.ml
1. I added support for calling into FStarC.Profiling for the Pulse checker, and used it in a couple of places. 
Profiling revealed the checking unfolds requires proving `slprop_equiv p q`, where `q` is a head normal form of `p`. However, by applying slprop_equiv_refl directly to such a goal, the proof procedes by unification in teq, slowly unfolding p and q to match. In an example from evercddl, this was taking around 20s.
So, 
2. I am now checking unfold (and fold) using slprop_equiv_unfold (resp. fold), which first uses transitivity, then a step of normalization, and then two applications of reflexivity, which then matches exactly. The resulting unfold proof now only takes about 100ms
=> Profiling and revising slprop_equiv checking for fold and unfold

.devcontainer/fromscratch/minimal.Dockerfile, .github/setup-macos.sh, .github/workflows/nightly.yml, pulse2rust/src/ocaml/Cargo.toml, pulse2rust/src/ocaml/rust/src/lib.rs
pulse2rust no longer builds with OCaml 5.3.0 (and make test fails for me locally).  However the new ocaml-interop crate version supports *only* OCaml 5.x.  So we need to bump both the OCaml version and the ocaml-interop dependency to support OCaml 5, which is now recommended for dev setups.
This also requires an update to the dev container image.
=> Bump CI to OCaml 5.3

test/pool/domainslib/driver.ml, test/pool/pulse_task/driver.ml
With 1e5 elements these tests take 5s on my machine.  This makes it really slow to run make in the test directory.  Reducing the element count brings the make runtime to half a second.
=> Speed up quicksort tests.

pulse2rust/tests/src/pulsetutorial_array.rs, src/checker/Pulse.Checker.Pure.fst, test/LetMutImps.fst
And more, just set the inst_extra flag to true in `check_term`. We have an expected type set, so this should be fine.
Fixes the first two functions in the added test case, which failed:
```fstar
fn test ()
{
let mut r : int = zero;
();
}
fn test2 ()
{
let mut p : ref int = null;
();
}
```
=> Checker: instantiating implicits at the end of initializers

lib/common/Pulse.Lib.Core.fsti, lib/common/Pulse.Lib.Tactics.fst, lib/common/Pulse.Lib.Tactics.fsti, mk/checker.mk, src/checker/Pulse.Checker.Pure.fst
Calling tcresolve works, and allows us to use the typeclass system to extend the set of non-informative types, but comes at a cost. For once, tcresolve will try to apply local instances from the enviroment beofre attempting to apply global ones, which means traversing the entire environment and, for each binder, normalizing it and attempting to unify it with the goal.
tcresolve should probably have smarter defaults, but, we also don't need to call it directly. This PR adds a custom tactic that has a fastpath for the common cases and only calls tcresolve if it could not solve the goal.
See the perf improvement in just building lib-pulse. Left is before, right is after:
=> Use a custom tactic for finding non_informative proofs

src/checker/Pulse.Checker.While.fst, src/checker/Pulse.Typing.Env.fst, src/checker/Pulse.Typing.Env.fsti, src/checker/Pulse.Typing.fst
This does not seem to have a big impact on synthetic tests, but seems strictly better than recomputing this every time.
=> Pulse.Typing.Env: making elab_env O(1)

test/MatchBasic.fst.output.expected, test/Test.Recursion.fst.output.expected, test/bug-reports/Bug.DesugaringError.fst.output.expected, test/bug-reports/Bug.SpinLock.fst.output.expected, test/bug-reports/Bug100.fst.output.expected, test/bug-reports/Bug107.fst.output.expected, test/bug-reports/Bug111.fst.output.expected, test/bug-reports/Bug113.fst.output.expected, test/bug-reports/Bug169.fst.output.expected, test/bug-reports/Bug174.fst.output.expected, test/bug-reports/Bug206.fst.output.expected, test/bug-reports/Bug266.fst.output.expected, test/bug-reports/Bug267.fst.output.expected, test/bug-reports/Bug274.fst.output.expected, test/bug-reports/Bug278.fst.output.expected, test/bug-reports/Bug29.fst.output.expected, test/bug-reports/Bug36.fst.output.expected, test/bug-reports/Bug45.fst.output.expected, test/bug-reports/Bug59.fst.output.expected, test/bug-reports/Bug94.fst.output.expected, test/bug-reports/BugHigherOrderApplication.fst.output.expected, test/bug-reports/ExistsErasedAndPureEqualities.fst.output.expected, test/bug-reports/IntroGhost.fst.output.expected, test/bug-reports/PartialApp.fst.output.expected, test/nolib/Annots.fst.output.expected, test/nolib/Bug416.fst.output.expected, test/nolib/MatchRange.fst.output.expected, test/nolib/Test.Matcher.fst.output.expected, test/nolib/Test.RewriteBy.fst.output.expected
=> Update expected error output, after F* patch

share/pulse/examples/dice/cbor/CBOR.Pulse.fst, share/pulse/examples/dice/cbor/CBOR.Spec.Const.fst, share/pulse/examples/dice/cbor/CBOR.Spec.Type.fsti, share/pulse/examples/dice/cbor/Makefile
Pulse's DPE example is used in EverCDDL's DPE test, but I have not migrated CBOR in Pulse's DPE example to new EverCBOR/EverCDDL yet.
For now, this commit avoids name clashes in the respective CBOR modules.
=> DPE example: CBOR.Spec.Constants -> CBOR.Spec.Const

src/ml/FStarC_Parser_Parse.mly, src/ml/pulseparser.mly, test/nolib/QuantifierOps.fst
Note: the parser is spitting out a lot of conflicts.
Warning: 28 states have shift/reduce conflicts.
Warning: one state has reduce/reduce conflicts.
Warning: 338 shift/reduce conflicts were arbitrarily resolved.
Warning: one reduce/reduce conflict was arbitrarily resolved.
Warning: 232 end-of-stream conflicts were arbitrarily resolved.
These are not introduced (nor fixed) by this patch.
=> parser: allow nested quantifiers at the top level

src/checker/Pulse.Simplify.fst, src/checker/Pulse.Simplify.fsti
I measure that repeatedly calling T.hua on a term to try to simplify it has a small but noticeable overhead: E.g., in Test.Basic1.fst we spend about 150ms in the prover, and about 50ms of that is eliminated by this optimization.
Going further, I wonder how useful it is to apply these simplifications to an slprop at all. This is only trying to simplify things like reveal/hide, projections etc. at the head of a term.
=> Some optimization in Pulse.Simplify: do not repeatedly call T.hua

src/checker/Pulse.Elaborate.Pure.fst, src/checker/Pulse.Syntax.Pure.fst, test/UnfoldMetaArg.fst
This failed:
```fstar
let my_pts_to (r : ref int) (#[exact (`1.0R)] f:perm) (v:int) : slprop =
Pulse.Lib.Reference.pts_to r #f v
fn add1 (r : ref int)
preserves my_pts_to r 1
{
unfold my_pts_to;
(* ^ Used to fail with
* Error 228:
- 'norm_term' failed
- Cannot type Pulse.Lib.Reference.pts_to ?r ?p ?n in context [x; x; x; x; x]
- Expected a function.
- Got an expression of type: Pulse.Lib.Core.slprop
- See also Pulse.Checker.AssertWithBinders.fst:152.15-152.73
*)
fold   my_pts_to;
();
}
```
=> Fix tm_pureapp for meta/tc implicit args

src/checker/Pulse.Checker.Bind.fst, src/checker/Pulse.Checker.Match.fst, src/checker/Pulse.Checker.fst, src/checker/Pulse.Extract.Main.fst, src/checker/Pulse.Syntax.Base.fsti, src/checker/Pulse.Typing.Env.fst, src/checker/Pulse.Typing.Env.fsti, test/bug-reports/Bug.SpinLock.fst.output.expected, test/bug-reports/Bug266.fst.output.expected, test/bug-reports/ExistsErasedAndPureEqualities.fst.output.expected, test/bug-reports/IntroGhost.fst.output.expected
I'm tired of looking at log files without variable names because we replace them with `x` before passing them to F*.
Before:
`try_teq of FStar.Pervasives.Native.tuple2 and FStar.Pervasives.Native.tuple2 in [Binding_var x, Binding_var x, Binding_var x, Binding_var x, Binding_var x, Binding_var x] {`
After:
`try_teq of FStar.Pervasives.Native.tuple2 and FStar.Pervasives.Native.tuple2 in [Binding_var __, Binding_var v, Binding_var i, Binding_var p, Binding_var s, Binding_var t] {`
The only awkward part is that we used to use the binder name `_` a *lot*.  However this name is treated specially in F*, in particular assumptions with this name seem to be dropped in the SMT encoding.  Therefore this PR changes the name to `__` instead.  Right before extraction we change it back to `_`, because …
=> Do not discard names in elab_env.

src/checker/Pulse.Checker.AssertWithBinders.fst, src/checker/Pulse.Checker.If.fst, src/checker/Pulse.Checker.ImpureSpec.fst, src/checker/Pulse.Checker.ImpureSpec.fsti, src/checker/Pulse.Checker.Match.fst, src/checker/Pulse.Checker.Rewrite.fst, src/checker/Pulse.Syntax.Base.fst, src/checker/Pulse.Syntax.Base.fsti, src/checker/Pulse.Syntax.Builder.fst, src/checker/Pulse.Syntax.Naming.fsti, src/ml/PulseSyntaxExtension_SyntaxWrapper.ml, test/ImpureSpec.fst
Fixes #481.
I'm pretty sure that `with x. unfold foo (!y) x` doesn't work yet because of the way we infer the binder type for `x`.  But this will change anyhow as we move over to uvars; so I'm leaving this out for now.
=> Support purification inside rewrite and unfold.

lib/pulse/lib/Pulse.Lib.Pervasives.fst, lib/pulse/lib/Pulse.Lib.Task.fst
The duplicable instance for emp is particularly useful for introducing shifts.
=> More duplicable instances.

lib/common/Pulse.Lib.Core.fsti, lib/core/Pulse.Lib.Core.fst, lib/core/PulseCore.Action.fst, lib/core/PulseCore.Action.fsti, lib/core/PulseCore.Atomic.fst, lib/core/PulseCore.Atomic.fsti, lib/core/PulseCore.BaseHeapSig.fst, lib/core/PulseCore.BaseHeapSig.fsti, lib/core/PulseCore.Heap2.fst, lib/core/PulseCore.Heap2.fsti, lib/core/PulseCore.IndirectionTheorySep.fst, lib/core/PulseCore.IndirectionTheorySep.fsti, lib/core/PulseCore.MemoryAlt.fst, lib/core/PulseCore.MemoryAlt.fsti, lib/pulse/lib/Pulse.Lib.GhostReference.fst, lib/pulse/lib/Pulse.Lib.GhostReference.fsti, lib/pulse/lib/Pulse.Lib.HigherGhostReference.fst, lib/pulse/lib/Pulse.Lib.HigherGhostReference.fsti
Null ghost references are a useful default value for when you're building recursive and circular ghost data structures.
=> Null ghost references.

lib/pulse/lib/Pulse.Lib.Borrow.fst, lib/pulse/lib/Pulse.Lib.Borrow.fsti, test/BorrowsExample.fst
This PR adds a lifetime-based API to simplify managing read-only resources.
For example, a read-only fractional permission to the reference `x` is represented as `x |-> Frac p y`.  This resource is not duplicable, and sharing it requires bookkeeping to get back the full `x |-> y` resource at the end.
By contrast, with lifetime-bounded resources a read-only reference `x` is represented as `bpts_to a x y`--intuitively meaning that we have read permission while the lifetime `a` is alive.  Sharing `bpts_to a x y` is trivial: it is duplicable and can be shared freely.  Reading `x` preserves the `lifetime_alive a` resource which needs to be threaded around.
The included test shows how to take several overlapping slices of an array (and how to implement functions using the bpts_to construction): …
=> Lifetimes and borrows
